version: "3"

services:
    web:
        build:
            context: php

        ports:
            - "80:80"
            - "9000:9000"

        volumes:
            - ${TDIW_HOME}/tdiw:/var/www/html
        
        environment: 
            - MYSQL_PASSWORD=demodemo
            - XDEBUG_CONFIG=192.168.1.80

    db:
        image: mariadb:10.1.38

        environment:
            - MYSQL_ROOT_PASSWORD=demodemo
            - MYSQL_DATABASE=tdiwb8
            - MYSQL_USER=tdiw-b8
            - MYSQL_PASSWORD=demodemo
        

    phpmyadmin:
        image: phpmyadmin:latest

        environment:
            - MYSQL_ROOT_PASSWORD=demodemo
            - MYSQL_DATABASE=tdiwb8
            - MYSQL_USER=tdiw-b8
            - MYSQL_PASSWORD=demodemo
            - PMA_HOST=db

        ports:
            - "8080:80"